# Generated by Django 5.2.7 on 2025-11-05 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.users",
                    ),
                ),
                ("pesa_points", models.BigIntegerField(default=0)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("farmer", "Farmer"),
                            ("engineer", "Engineer"),
                            ("doctor", "Doctor"),
                            ("artist", "Artist"),
                            ("entrepreneur", "Entrepreneur"),
                            ("writer", "Writer"),
                            ("athlete", "Athlete"),
                        ],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("streak_days", models.IntegerField(default=0)),
                ("streak_saved_at", models.DateField(blank=True, null=True)),
                (
                    "avatar_url",
                    models.CharField(default="avatars/teacher_1.png", max_length=255),
                ),
                ("total_dreams_unlocked", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="StreakRescues",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("points_sacrificed", models.IntegerField(default=50)),
                ("rescued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescues_received",
                        to="accounts.users",
                    ),
                ),
                (
                    "savior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescues_given",
                        to="accounts.users",
                    ),
                ),
            ],
            options={
                "db_table": "streak_rescues",
            },
        ),
        migrations.CreateModel(
            name="Friendships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to="accounts.users",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to="accounts.users",
                    ),
                ),
            ],
            options={
                "db_table": "friendships",
            },
        ),
    ]
