# Generated by Django 5.2.7 on 2025-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("societies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiles",
            name="societies",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="societies.societies"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streakrescues",
            unique_together={("savior", "saved", "rescued_at")},
        ),
        migrations.AlterUniqueTogether(
            name="friendships",
            unique_together={("user", "friend")},
        ),
    ]
