# Generated by Django 5.1.3 on 2025-11-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dreams',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(unique=True)),
                ('cost', models.BigIntegerField()),
                ('order_index', models.IntegerField(unique=True)),
                ('image_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisite_dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dreams.dreams')),
            ],
            options={
                'db_table': 'dreams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDreams',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dreams.dreams')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'user_dreams',
                'managed': True,
                'unique_together': {('user', 'dream')},
            },
        ),
    ]
