# Generated by Django 5.1.3 on 2025-11-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardGlobal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.users')),
                ('pesa_points', models.BigIntegerField(blank=True, null=True)),
                ('dreams_unlocked', models.IntegerField(blank=True, null=True)),
                ('games_won', models.IntegerField(blank=True, null=True)),
                ('week_start', models.DateField()),
            ],
            options={
                'db_table': 'leaderboard_global',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSociety',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pesa_points', models.BigIntegerField(blank=True, null=True)),
                ('week_start', models.DateField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='societies.societies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'leaderboard_society',
                'managed': True,
                'unique_together': {('society', 'user', 'week_start')},
            },
        ),
    ]
