# Generated by Django 5.1.3 on 2025-11-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRooms',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player_count', models.IntegerField(blank=True, null=True)),
                ('current_turn', models.IntegerField(blank=True, default=0, null=True)),
                ('dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dreams.dreams')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'game_rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GamePlayers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('seat', models.IntegerField(blank=True, default=0, null=True)),
                ('starting_points', models.BigIntegerField(blank=True, null=True)),
                ('current_points', models.BigIntegerField(blank=True, null=True)),
                ('savings', models.BigIntegerField(blank=True, null=True)),
                ('liabilities', models.BigIntegerField(blank=True, null=True)),
                ('assets', models.JSONField(blank=True, null=True)),
                ('spending_cards', models.JSONField(blank=True, null=True)),
                ('savings_cards', models.JSONField(blank=True, null=True)),
                ('tokens', models.JSONField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('is_cpu', models.BooleanField(blank=True, null=True)),
                ('ready', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.gamerooms')),
            ],
            options={
                'db_table': 'game_players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameLogs',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('turn', models.IntegerField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.gamerooms')),
            ],
            options={
                'db_table': 'game_logs',
                'managed': True,
            },
        ),
    ]
