# Generated by Django 5.1.3 on 2025-11-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaQuestions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('profession', models.TextField()),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.IntegerField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qa_questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserQaAnswers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_date', models.DateField()),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa.qaquestions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'user_qa_answers',
                'managed': True,
                'unique_together': {('user', 'question', 'answered_date')},
            },
        ),
    ]
