# Generated by Django 5.1.3 on 2025-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('purchase_cost', models.BigIntegerField()),
                ('profit_per_return', models.BigIntegerField()),
                ('max_returns', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventCards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('effect_points', models.BigIntegerField()),
                ('message', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('rarity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SavingsCards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('save_threshold', models.BigIntegerField()),
                ('bonus_condition', models.JSONField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'savings_cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpendingCards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('total_cost', models.BigIntegerField()),
                ('breakdown', models.JSONField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spending_cards',
                'managed': True,
            },
        ),
    ]
